apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: todoapp
  namespace: todoapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: todoapp
  minReplicas: { .Value.hpa.todoapp.minReplicas }
  maxReplicas: { .Value.hpa.todoapp.maxReplicas }
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: { .Value.hpa.todoapp.cpuUtilization }
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: { .Value.hpa.todoapp.memoryUtilization }
