apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  namespace: todoapp
spec:
  storageClassName: standard
  persistentVolumeReclaimPolicy: Delete
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ .Values.persistentVolume.todoapp.capacity }}
  hostPath:
    path: /data/
