apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  namespace: {{ .Values.common.namespace }}
type: Opaque
data:
{{- range $key, $val := .Values.todoapp.secret }}
  {{ $key | upper }}: {{ $val | b64enc | quote}}
{{- end -}}
