namespace:
  todoapp:
    name: todoapp-helm
  mysql:
    name: mysql-helm

secrets:
  - name: secret1
    data:
      key1: value1
  - name: secret2
    data:
      key2: value2
resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

affinity:
    nodeAffinity:
      key: app
      values:
        - "todoapp"
        - "value2"

image:
  todoapp:
    repository: yikulyk404/todoapp:4.0.1
    tag: "4.0.1"

hpa:
  todoapp:
    minReplicas: 2
    maxReplicas: 5
    cpuUtilization: 70
    memoryUtilization: 70

persistentVolume:
  todoapp:
    capacity: "1Gi"

persistentVolumeClaim:
  todoapp:
    storage: "1Gi"

serviceAccount: todoapp
