namespace:
  name: todoapp-helm

secrets:
  - name: secret1
    data:
      key1: value1
  - name: secret2
    data:
      key2: value2
resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

affinity:
    nodeAffinity:
      key: app
      values:
        - "todoapp"
        - "value2"

image:
  repository: yikulyk404/todoapp:4.0.1
  tag: "4.0.1"

hpa:
  minReplicas: 1
  maxReplicas: 10
  cpuUtilization: 50
  memoryUtilization: 70

persistentVolume:
  capacity: "1Gi"

persistentVolumeClaim:
  storage: "1Gi"

serviceAccount: todoapp
