namespace:
  mysql:
    name: mysql-helm
mysql:
  secrets:
      MYSQL_ROOT_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
      MYSQL_USER: "YXBwX3VzZXI=" # Base64 encoding for "app_user"
      MYSQL_PASSWORD: "MTIzNA==" # Base64 encoding for "1234"
  resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"

  rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%

  affinity:
      nodeAffinity:
        values: mysql


image:
  mysql:
    repository: mysql:8.0
    tag: "8.0"

hpa:
  mysql:
    minReplicas: 2
    maxReplicas: 10
    cpuUtilization: 50
    memoryUtilization: 70

persistentVolume:
  capacity: "1Gi"

persistentVolumeClaim:
  storage: "1Gi"

serviceAccount: mysql
