namespace:
  mysql:
    name: mysql-helm

secrets:
  mysql:
    - name: MYSQL_ROOT_PASSWORD
      data:
        key1: "MTIzNA=="
    - name: MYSQL_USER
      data:
        key2: "YXBwX3VzZXI="
    - name: MYSQL_PASSWORD
      data:
        key3: "MTIzNA=="
resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "256Mi"

rollingUpdate:
    maxUnavailable: 25%
    maxSurge: 25%

affinity:
    nodeAffinity:
      key: app
      values:
        - "mysql"


image:
  mysql:
    repository: mysql:8.0
    tag: "8.0"

hpa:
  mysql:
    minReplicas: 2
    maxReplicas: 10
    cpuUtilization: 50
    memoryUtilization: 70

persistentVolume:
  capacity: "1Gi"

persistentVolumeClaim:
  storage: "1Gi"

serviceAccount: mysql
