apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: mysql
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: { .Value.secters.mysql.name.key1 | b64enc | quote } # Base64 encoding for "1234"
  MYSQL_USER: { .Value.secters.mysql.name.key2 | b64enc | quote } # Base64 encoding for "app_user"
  MYSQL_PASSWORD: { .Value.secters.mysql.name.key3 | b64enc | quote } # Base64 encoding for "1234"